// Test generated by RoostGPT for test React_Unit_Test2 using AI Type Open AI and AI Model gpt-4


import React from "react";
import { render, fireEvent, cleanup } from '@testing-library/react';
import LeadForm from './LeadForm';
import { Form } from "antd";

afterEach(cleanup);

describe('LeadForm', () => {
  test('renders correctly', () => {
    const { asFragment } = render(<LeadForm />);
    expect(asFragment()).toMatchSnapshot();
  });

  test('shows error messages when fields are empty and form is submitted', () => {
    const { getByText } = render(<LeadForm />);
    const form = getByText('Submit');

    fireEvent.submit(form);

    expect(getByText('Please input your client name!')).toBeInTheDocument();
    expect(getByText('Please input your phone!')).toBeInTheDocument();
    expect(getByText('Please input your E-mail!')).toBeInTheDocument();
    expect(getByText('Please input date!')).toBeInTheDocument();
    expect(getByText('Please input your budget!')).toBeInTheDocument();
  });

  test('validates email input', () => {
    const { getByLabelText, getByText } = render(<LeadForm />);
    const emailInput = getByLabelText('E-mail');

    fireEvent.change(emailInput, { target: { value: 'invalid email' } });
    fireEvent.blur(emailInput);

    expect(getByText('The input is not valid E-mail!')).toBeInTheDocument();
  });
});
