// Test generated by RoostGPT for test React_Unit_Test2 using AI Type Open AI and AI Model gpt-4


import React from 'react';
import { render, fireEvent } from '@testing-library/react';
import '@testing-library/jest-dom/extend-expect';
import { Form } from 'antd';
import ProductForm from './ProductForm';

describe('ProductForm', () => {
  let getByTestId;

  beforeEach(() => {
    ({ getByTestId } = render(<ProductForm />));
  });

  test('renders product name input', () => {
    const productNameInput = getByTestId('productName');
    expect(productNameInput).toBeInTheDocument();
  });

  test('renders product description input', () => {
    const descriptionInput = getByTestId('description');
    expect(descriptionInput).toBeInTheDocument();
  });

  test('renders product price input', () => {
    const priceInput = getByTestId('price');
    expect(priceInput).toBeInTheDocument();
  });

  test('validates product name input on blur', () => {
    const productNameInput = getByTestId('productName');
    fireEvent.blur(productNameInput);
    expect(productNameInput).toHaveClass('ant-form-item-has-error');
  });

  test('validates product description input on blur', () => {
    const descriptionInput = getByTestId('description');
    fireEvent.blur(descriptionInput);
    expect(descriptionInput).toHaveClass('ant-form-item-has-error');
  });

  test('validates product price input on blur', () => {
    const priceInput = getByTestId('price');
    fireEvent.blur(priceInput);
    expect(priceInput).toHaveClass('ant-form-item-has-error');
  });
});
