// Test generated by RoostGPT for test React_Unit_Test2 using AI Type Open AI and AI Model gpt-4


import { render } from "@testing-library/react";
import DynamicForm from "./index.jsx";

describe('DynamicForm', () => {
  let fields = [];

  beforeEach(() => {
    fields = [
      { type: 'input', label: 'First Name', key: 'firstName' },
      { type: 'input', label: 'Last Name', key: 'lastName' },
      { type: 'checkbox', label: 'Accept Terms', key: 'terms' }
    ];
  });

  test('should render all form fields', () => {
    const { getByLabelText } = render(<DynamicForm fields={fields} />);
    expect(getByLabelText('First Name')).toBeInTheDocument();
    expect(getByLabelText('Last Name')).toBeInTheDocument();
    expect(getByLabelText('Accept Terms')).toBeInTheDocument();
  });

  test('should not render any fields if fields array is empty', () => {
    fields = [];
    const { container } = render(<DynamicForm fields={fields} />);
    expect(container.firstChild).toBeNull();
  });

  test('should handle unknown field type', () => {
    fields.push({ type: 'unknown', label: 'Unknown', key: 'unknown' });
    const { getByLabelText } = render(<DynamicForm fields={fields} />);
    expect(getByLabelText('Unknown')).not.toBeInTheDocument();
  });
});
